<BarShowcaseScreen>

    BoxLayout:
        orientation: "vertical"

        TopBar:
            id: topbar

        CupertinoNavigationBar:

            BoxLayout:

                CupertinoSystemButton:
                    text: "Back"

                CupertinoLabel:
                    text: "CupertinoNavigationBar"

                CupertinoSystemButton:
                    text: "Back"


        CupertinoTabBar:
            id: tab_bar
            size_hint_y: 0.1
