<ButtonShowcaseScreen>

    BoxLayout:
        orientation: "vertical"

        TopBar:
            id: topbar

        BoxLayout:
            spacing: "10dp"
            padding: "20dp"
            orientation: "vertical"

            CupertinoButton:
                text: 'CupertinoButton'

            CupertinoSystemButton:
                text: 'CupertinoSystemButton'

            CupertinoSymbolButton:
                symbol: 'info'
