<PageShowcaseScreen>

    BoxLayout:
        orientation: "vertical"

        TopBar:
            id: topbar

        CupertinoScreenManager:

            CupertinoPageControls:

                CupertinoLabel:
                    text: "Screen 1"

            CupertinoPageControls:

                CupertinoLabel:
                    text: "Screen 2"

            CupertinoPageControls:

                CupertinoLabel:
                    text: "Screen 3"
